language: python


matrix:
  include:
    - python: 2.7


# follow blaze example and setup cond env 
install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION pytest cython
  - source activate test-environment

  # Install coveralls
  #- pip install coveralls

  # Install polygon example
  - python setup.py install

script:
  - echo '[pytest]' > pytest.ini
  - echo 'addopts = -vv -r sxX --pyargs polygon' >> pytest.ini
  - py.test --pyargs polygon
  #- coverage run $(which py.test)
  #- coverage report --show-missing 

#after_success:
#    - coveralls

notifications:
    email: 
        - jsandhu@continuum.io
