#!/usr/bin/env python
import os
import shutil

from setuptools import setup, find_packages
from distutils.command.clean import clean
from distutils.extension import Extension

# if cythonize is not used - need to use Cython's build_ext
# so it autogenerates the C++ code before compiling
# look into cythonize as well - may require building libpolygon separately 
from Cython.Distutils import build_ext


base = os.path.dirname(__file__)
pkg_name = 'polygon'

cy_poly_dir = os.path.join(base, 'polygon')
lib_poly_dir = os.path.join(base, 'lib_polygon')


class cleandev(clean):
    description = ("cleans files generated by 'develop' mode and files "
                   "autogenerated by cython")

    def run(self):
        # call base class clean
        clean.run(self)
        dirs = ['build', pkg_name + '.egg-info']
        for d in dirs:
            try:
                d_full = os.path.join(base, d)
                shutil.rmtree(d_full)
                print('removoed ' + d_full)
            except:
                pass

        # remove auto gen cython files
        auto_gen = ['cy_polygon.so', 'libpolygon.so', 'cy_polygon.cpp']
        for f in auto_gen:
            f_full = os.path.join(base, 'polygon', f)
            try:
                os.remove(f_full)
                print('removed ' + f_full)
            except:
                pass


# let's build the lib_polygons separately and link to it
#===============================================================================
# exts = [Extension("polygon.libpolygon",
#                   [os.path.join(lib_poly_dir, 'polygon.cpp')],
#                   language="c++",
#                   include_dirs=[os.path.join(base, 'lib_polygons')],
#                   )]
#===============================================================================
exts = []
exts.append(Extension("polygon.cy_polygon",
                      [os.path.join(lib_poly_dir, 'polygon.cpp'),
                       os.path.join(cy_poly_dir, 'cy_polygon.pyx')],
                      language="c++",
                      include_dirs=[os.path.join(base, 'polygon'),
                                    lib_poly_dir]
                      ))

setup(name=pkg_name,
      cmdclass={'build_ext': build_ext,
                'cleandev': cleandev},
      version='0.1',
      description='This is a demo package',
      ext_modules=exts,
      packages=find_packages())