#!/usr/bin/env python
import os
import shutil

from setuptools import setup, find_packages
from distutils.command.clean import clean
from distutils.extension import Extension

# if cythonize is not used - need to use Cython's build_ext
# so it autogenerates the C++ code before compiling
# look into cythonize as well - may require building libpolygon separately 
from Cython.Distutils import build_ext


base = os.path.dirname(__file__)
pkg_name = 'polygon'

cy_poly_dir = os.path.join(base, 'polygon')
lib_poly_dir = os.path.join(base, 'lib_polygon')


class cleandev(clean):
    description = ("cleans files generated by 'develop' mode and files "
                   "autogenerated by cython")

    def run(self):
        # call base class clean
        clean.run(self)
        dirs = ['build', pkg_name + '.egg-info', 'dist']
        for d in dirs:
            try:
                d_full = os.path.join(base, d)
                shutil.rmtree(d_full)
                print('removoed ' + d_full)
            except:
                pass

        # remove auto gen cython files
        auto_gen = ['cy_polygon.so', 'libpolygon.so', 'cy_polygon.cpp']
        for f in auto_gen:
            f_full = os.path.join(base, 'polygon', f)
            try:
                os.remove(f_full)
                print('removed ' + f_full)
            except:
                pass


# let's build the lib_polygons separately and link to it
#===============================================================================
# exts = [Extension("polygon.libpolygon",
#                   [os.path.join(lib_poly_dir, 'polygon.cpp')],
#                   language="c++",
#                   include_dirs=[os.path.join(base, 'lib_polygons')],
#                   )]
#===============================================================================

exts = []
exts.append(Extension("polygon.cy_polygon",
                      [os.path.join(lib_poly_dir, 'polygon.cpp'),
                       os.path.join(cy_poly_dir, 'cy_polygon.pyx')],
                      language="c++",
                      include_dirs=[os.path.join(base, 'polygon'),
                                    lib_poly_dir],
                      # add external libraries for testing only
                      libraries=['z', 'curl'],
                      ))

# tested on Mac OSX (10.10.3), with setuptools 17.1.1, py27_0 
# zip_safe flag below is ignored - so install using the install_egg_info command
# need egg-info folder since package contains compiled code
# ./setup.py install_egg_info 
setup(name=pkg_name,
      cmdclass={'build_ext': build_ext,
                'cleandev': cleandev},
      version='0.2',
      description='introduce build error in demo package',
      author="Jasmine Sandhu",
      author_email="jsandhu@continuum.io",
      url= "https://github.com/sandhujasmine/CythonExample",
      ext_modules=exts,
      packages=['polygon'],
      zip_safe=False)
