package:
  name: polygon
  version: 0.1

source:
  git_tag: v0.1
  git_url: https://github.com/sandhujasmine/CythonExample.git

build:
  # preserve egg dir since we have compiled code
  preserve_egg_dir: yes
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - cython
    - pytest

  run:
    - python

test:
  imports:
    - polygon
   
  requires:
    - pytest

  # note: I believe tests are run upon build, not upon install - so following was failing
  # when installed with --use-local
  #commands:
  #  - py.test --pyargs -v polygon

about:
  home: https://github.com/sandhujasmine/CythonExample
  license: xxx
  summary: "polygon is an example cython package built using conda install"

#app:
#  own_environment: true
