package:
  name: polygon
  version: {{environ.get('GIT_DESCRIBE_TAG', '')}}

source:
  # this should break - repro error due to linking against incorrect libcurl version
  path: ../

build:
  number: {{environ.get('GIT_DESCRIBE_NUMBER', 0)}}
  # preserve egg dir since we have compiled code
  preserve_egg_dir: yes
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - cython
    - pytest
    - netcdf4   # only for testing

  run:
    - python
    - netcdf4   # only for testing
    - ipython   # also for testing
    - pytest    # for testing

test:
  imports:
    - polygon
   
  requires:
    - pytest

  # note: I believe tests are run upon build, not upon install - so following was failing
  # when installed with --use-local
  #commands:
  #  - py.test --pyargs -v polygon

about:
  home: https://github.com/sandhujasmine/CythonExample
  license: xxx
  summary: "polygon is an example cython package built using conda install"
